version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '3000:3000' # Run server port
      - '5858:5858' # Debug port
    restart: always
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE={{projectName}}-db
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql
