# LTS image from docker hub
FROM node:16.16.0-alpine3.16

# Create app directory
WORKDIR /usr/src/app

# Copy local files to the docker image
COPY . /usr/src/app

# Install dependencies
RUN npm install
# Run migrations
RUN npm run db:migrate

# Expose the port where the app will run
EXPOSE 3000

# Start the application
CMD [ "npm", "run", "dev" ]

